version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # build and run tests
      - run:
          name: build and run tests
          command: |
            docker build -t sift .
      - deploy:
          name: push docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              TAG=0.$CIRCLE_BUILD_NUM
              echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
              docker tag sift "maximz/sift:${TAG}"
              docker tag sift "maximz/sift:latest"
              docker push "maximz/sift:${TAG}"
              docker push "maximz/sift:latest"
            fi